- lib/get_it.dart
- test/get_it_test.dart
Removed adicional map.remove on wrong place, changed optional named parameters to optional positional and renaming disposal function to disposingFunction
> feature(unregister): fixes some appointments from PR #15

- lib/get_it.dart
When call unregister with no disposing function, then call of disposingFunction is not checked, throwing NoSuchMethodError: The method 'call' was called on null.
Steps to reproduce:
```dart
GetIt.I.registerSingleton("Value");
try {
GetIt.I.unregister<String>();
} catch (ex) {
print(ex); // NoSuchMethodError: The method 'call' was called on null.
}
```
> Fix unregister bug when no disposing function provided

- lib/get_it.dart
- test/get_it_test.dart
When the user calls `asNewInstance`, they are already indicating that they know what they're doing - we don't need to add an extra safety to this
> Remove allowMultipleInstances

- lib/get_it.dart
- test/get_it_test.dart
Currently, this code snippet fails:
```dart
import 'package:get_it/get_it.dart';
void main(){
GetIt.I.registerSingleton<String>("test", instanceName: "instanceName");
final myString = GetIt.I<String>("instanceName");
print(myString);
}
```
with the message:
```
Unhandled exception:
Invalid argument(s): Object with name instanceName has a different type (String) than the one that is inferred (String) where you call it
#0      GetIt.get (package:get_it/get_it.dart:80:11)
#1      GetIt.call (package:get_it/get_it.dart:98:12)
#2      main (package:neocortex_mobile/get_it_test.dart:9:27)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
The reason for this is, …
> Fix wrong type checking when using instanceName in combination with generic type parameter

- lib/get_it.dart
- test/get_it_test.dart
> Add support to reset lazy singleton instance

- README.md
Great library. There were some typo's in the readme.
> Some typo's

- .editorconfig
- example/lib/main.dart
- lib/get_it.dart
- lib/get_it_impl.dart
- pubspec.yaml
In a production app I used get_it and I had a crash with the nullsafety branch. Turns out that `isRegistered()` calls `_findFactoryByNameAndType()` which throws an exception because the returned value is null, but is silenced using the bang (!) character.
So I fixed that and also reformatted the source code to 100 characters per line (it was not formatted it seemed). Also, many English grammatical and pronunciation errors were fixed.
> Formatted lines with 80 characters, null crash fix, English fixes

- pubspec.yaml
bumping Flutter dependencies to their prerelease versions since 1.26 got bumped to the beta channel.
> fix #160: bump to null-safety prerelease versions

- lib/get_it_impl.dart
- test/get_it_test.dart
Uses `await` only if the disposal function is a future in `resetLazySingleton` and `unregister`.
> improves disposal function used in resetLazySingleton and unregister

- lib/get_it_impl.dart
When registering a singleton that other singletons are dependent on, the instance's `objectsWaiting` list gets filled with the dependent singletons. This list is cleared for async singletons, when they have been created, as of [fix for #210](https://github.com/fluttercommunity/get_it/commit/dd9ad516c3d5b25a8350cd95cfc64884928e01a5).
The list is not cleared for non-async singletons, which results in them being unable to be unregistered at any time with the `StateError(
'There are still other objects waiting for this instance so signal ready'`.
This PR fixes the unexpected exception by clearing the `objectsWaiting` when a non-async singleton has been initialized.
> Fix StateError when unregistering non-async singletons other singletons are dependent on

- lib/get_it_impl.dart
As I described in #233 there is a duplicated whitespace in the error message:
This is because we are adding a second whitespace in the `instanceName  != null` check. But this is not necessary because we have here already our whitespace `...with $...`.
> Remove duplicated whitespace when showing already / not registered error

- lib/get_it.dart
- lib/get_it_impl.dart
- test/get_it_test.dart
**Current version:**
GetIt.I.resetLazySingleton(instance: YOUR-INSTANCE) throws when the generic is omitted.
**New version:**
Allows to reset the lazy Singleton by only providing an instance.
> Reset a lazy Singleton by providing an instance.

- README.md
Hi Thomas,
I have tried to fix some grammar mistakes in the documentation. I hope you will accept my contribution.
Thanks
Usama Karim
Flutter Developer
> Fix Grammer mistakes

- lib/get_it.dart
Hi @escamoteur, 
First of all thanks a lot for this great package. I stumbled upon this small probably smallest typo 😅  while reading docs. I really appreciate how well it is written👌 . Got to learn a lot while reading this package. Hope to learn more from you. 🙏
Regards 
Mitesh Singh 
@singhmitesh
> docs: fix small typo on line number 387 get_it.dart

- lib/get_it.dart
- lib/get_it_impl.dart
Just a convenience feature so you can write code like this:
```dart
final instance = GetIt.I.registerSingleton(Object());
```
> Return the instance when calling registerSingleton

- lib/get_it.dart
- lib/get_it_impl.dart
Added flag to suppress the printing of error messages. 
When a user is catching the error themselves and logging it this print is intrusive and should not appear. Default set to false to maintain past behaviour.
> Added flag to suppress the printing of error messages. 

- lib/get_it.dart
- lib/get_it_impl.dart
Add support for type parameter to "get/call" etc. functions. #298
> Add support form type

- README.md
- lib/get_it.dart
- lib/get_it_impl.dart
- test/scope_test.dart
In some cases, I need to check if the scope that I'm trying to push has already been pushed before.
There is an option to do it by setting the onScopeChanged callback and managing the scope changes in a stack somewhere in my sources, but as GetIt already manages the list of scopes, I believe the new `hasScope()` API can be a better way to check it.
> Added hasScope api to easily verify if the scope already pushed before

- lib/get_it.dart
- test/scope_test.dart
https://github.com/fluttercommunity/get_it/issues/326
I added a test but it fails for some reason.
TestClass is not removed after popScope().
> isFinal test

- CHANGELOG.md
- README.md
- doc/api/get_it/GetIt/reset.html
- lib/get_it.dart
- lib/get_it_impl.dart
- test/get_it_test.dart
There are a few situations, where one instance depends on an instance you created before.
In all of these situations, it makes more sense to dispose of the widgets in reverse order.
> Update get_it_impl.dart to dispose in reverse order

- CHANGELOG.md
CHANGELOG is formatted badly for pub.dev rendering.
This PR reformats markdown, so notes appear nicely and as intended.
Since the official release is already available, you can also just merge all pre's under 8.0.0.
> Fix CHANGELOG format for pub.dev

- test/scope_test.dart
Tests for changes related to https://github.com/fluttercommunity/get_it/issues/364
Specifically for commit 80132fca015c1b891829d1c820af47aacbdcb7fe
> Add tests for pushScopeInProgress

- lib/get_it_impl.dart
- test/skip_double_registration_test.dart
This PR fixes the behavior of the `skipDoubleRegistration` parameter. Previously, it ignored registration regardless of the `instanceName` value. Now, registration is only skipped if the `instanceName` matches, which is the expected behavior.
- Updated the logic for `skipDoubleRegistration` to take `instanceName` into account when deciding whether to skip registration.
This fix prevents situations where a registration could be mistakenly skipped even with different `instanceName` values, which caused incorrect behavior in certain scenarios.
- Tested with both unnamed registrations and those with `instanceName` values to ensure that registration is only skipped when names are the same and works as expected otherwise.
> fix: skipDoubleRegistration with instanceName

- lib/get_it_impl.dart
- test/get_it_test.dart
This Pr references issue #382 where an assertion  on the getObject method (and its async equivalent) blocks cached factories from having parameters passed.
The fix is adjusting the assertion to include the "cachedFactory" as a type.
While fixing this issue I also noticed that the lastParameters were not being saved in the cached factory section, which resulted in the cached factory functions being broken since this check always failed:
```dart
if (weakReferenceInstance?.target != null &&
param1 == lastParam1 &&
param2 == lastParam2)
```
Saving the lastParams when creating new instances fixes this.
Appropriate tests have been writen for the cached factory which were entirely missing earlier.
> Revise and improve cached factory handling with params

- lib/get_it.dart
- lib/get_it_impl.dart
- test/get_it_test.dart
- **Access Count Tracking** : We can now track how many times a singleton has been accessed using the `getAccessCount` method.
- **Clear All Instances** : The `clearAllInstances` method allows clearing all instances of a specific type, including named instances.
- **Set Default Instance** : The `setDefault` method allows setting or replacing the default instance for a type, with an option to use a named instance.
> Implement new methods for GetIt service locator

- lib/get_it_impl.dart
There was a default case in a switch statement, that could not be reached since the possible values of the switch statement are completely coververed.
This led to a reduces Pub Score on pub.dev
> Getting rid of static analysis warning on pub.dev

- lib/get_it.dart
- lib/get_it_impl.dart
- test/get_it_test.dart
If entities can be retrieved via type parameter, it makes sense to be able to check for registered entities via the same mechanism.
> Allow querying registrations by passing type parameter to isRegistered
